export const lesserTheme = {
  base: 'vs-dark',
  inherit: false,
  rules: [
    // Default text
    { token: '', foreground: 'C0C8D8' },
    { token: 'source', foreground: 'C0C8D8' },
    { token: 'text', foreground: 'C0C8D8' },
    
    // Comments
    { token: 'comment', foreground: '7A7595', fontStyle: 'italic' },
    { token: 'comment.block', foreground: '7A7595' },
    { token: 'comment.line', foreground: '7A7595' },
    { token: 'comment.block.documentation', foreground: '8A85A5', fontStyle: 'italic' },
    
    // Keywords - cyan color
    { token: 'keyword', foreground: '89DDFF' },
    { token: 'keyword.control', foreground: '89DDFF' },
    { token: 'keyword.control.flow', foreground: '89DDFF' },
    { token: 'keyword.control.import', foreground: '89DDFF' },
    { token: 'keyword.control.export', foreground: '89DDFF' },
    { token: 'keyword.operator.new', foreground: '89DDFF' },
    { token: 'keyword.operator.expression', foreground: '89DDFF' },
    
    // Storage - cyan color
    { token: 'storage', foreground: '89DDFF' },
    { token: 'storage.type', foreground: '89DDFF' },
    { token: 'storage.modifier', foreground: '89DDFF' },
    { token: 'storage.type.function', foreground: '89DDFF' },
    { token: 'storage.type.class', foreground: '89DDFF' },
    
    // Operators
    { token: 'operator', foreground: 'B8C0D0' },
    { token: 'keyword.operator', foreground: 'B8C0D0' },
    { token: 'keyword.operator.arithmetic', foreground: 'B8C0D0' },
    { token: 'keyword.operator.assignment', foreground: 'B8C0D0' },
    { token: 'keyword.operator.comparison', foreground: 'B8C0D0' },
    
    // Punctuation
    { token: 'delimiter', foreground: 'B8C0D0' },
    { token: 'delimiter.bracket', foreground: 'B0B8C8' },
    { token: 'delimiter.parenthesis', foreground: 'B0B8C8' },
    { token: 'delimiter.square', foreground: 'B0B8C8' },
    { token: 'delimiter.curly', foreground: 'B0B8C8' },
    { token: 'punctuation', foreground: 'B8C0D0' },
    { token: 'meta.brace', foreground: 'B0B8C8' },
    
    // Strings - salmon color
    { token: 'string', foreground: 'E8B89C' },
    { token: 'string.quoted', foreground: 'E8B89C' },
    { token: 'string.template', foreground: 'E8B89C' },
    { token: 'string.interpolated', foreground: 'E8B89C' },
    { token: 'string.regexp', foreground: '80FFB5' },

    // Numbers and constants - yellow color
    { token: 'number', foreground: 'FFE5A0' },
    { token: 'number.float', foreground: 'FFE5A0' },
    { token: 'number.hex', foreground: 'FFE5A0' },
    { token: 'constant', foreground: 'FFE5A0' },
    { token: 'constant.numeric', foreground: 'FFE5A0' },
    { token: 'constant.language', foreground: 'E8B89C' },
    { token: 'constant.language.boolean', foreground: 'E8B89C' },
    { token: 'constant.language.null', foreground: 'E8B89C' },
    { token: 'constant.character.escape', foreground: '80FFB5' },
    
    // Types and classes - teal color
    { token: 'type', foreground: '7AC0A0' },
    { token: 'type.identifier', foreground: '7AC0A0' },
    { token: 'class', foreground: '7AC0A0' },
    { token: 'class.identifier', foreground: '7AC0A0' },
    { token: 'entity.name.type', foreground: '7AC0A0' },
    { token: 'entity.name.class', foreground: '7AC0A0' },
    { token: 'support.type', foreground: '7AC0A0' },
    { token: 'support.class', foreground: '7AC0A0' },
    
    // Interfaces
    { token: 'interface', foreground: '7AC0A0' },
    { token: 'entity.name.type.interface', foreground: '7AC0A0' },
    
    // Enums
    { token: 'enum', foreground: '7AC0A0' },
    { token: 'enumMember', foreground: 'FFE5A0' },
    
    // Type parameters
    { token: 'typeParameter', foreground: '7AC0A0' },
    
    // Functions - purple color
    { token: 'function', foreground: 'C2A0FD' },
    { token: 'function.declaration', foreground: 'C2A0FD' },
    { token: 'entity.name.function', foreground: 'C2A0FD' },
    { token: 'support.function', foreground: 'C2A0FD' },
    { token: 'method', foreground: 'C2A0FD' },
    
    // Variables - yellow color
    { token: 'variable', foreground: 'FFE5A0' },
    { token: 'variable.other', foreground: 'FFE5A0' },
    { token: 'variable.parameter', foreground: 'FFE5A0' },
    { token: 'parameter', foreground: 'FFE5A0' },
    { token: 'variable.other.constant', foreground: 'FFE5A0' },
    { token: 'variable.language', foreground: '80FFB5' },
    { token: 'variable.language.this', foreground: '80FFB5' },
    { token: 'variable.language.self', foreground: '80FFB5' },
    
    // Properties - yellow color
    { token: 'property', foreground: 'FFE5A0' },
    { token: 'variable.other.property', foreground: 'FFE5A0' },
    { token: 'meta.property', foreground: 'FFE5A0' },

    // Namespace
    { token: 'namespace', foreground: 'C2A0FD' },
    
    // Decorators/Annotations
    { token: 'annotation', foreground: 'C2A0FD' },
    { token: 'decorator', foreground: 'C2A0FD' },
    { token: 'meta.decorator', foreground: 'C2A0FD' },
    
    // Tags (HTML/JSX)
    { token: 'tag', foreground: '80FFB5' },
    { token: 'tag.id', foreground: '80FFB5' },
    { token: 'metatag', foreground: '80FFB5' },
    { token: 'metatag.html', foreground: '80FFB5' },
    { token: 'metatag.xml', foreground: '80FFB5' },
    
    // Attributes
    { token: 'attribute.name', foreground: 'FFE5A0' },
    { token: 'attribute.value', foreground: 'E8B89C' },
    { token: 'attribute.value.html', foreground: 'E8B89C' },
    
    // JSON
    { token: 'string.key.json', foreground: 'FFE5A0' },
    { token: 'string.value.json', foreground: 'E8B89C' },
    { token: 'support.type.property-name.json', foreground: 'FFE5A0' },
    
    // CSS
    { token: 'attribute.name.css', foreground: 'FFE5A0' },
    { token: 'attribute.value.css', foreground: 'C0C8D8' },
    { token: 'attribute.value.number.css', foreground: 'FFE5A0' },
    { token: 'attribute.value.unit.css', foreground: 'E8B89C' },
    { token: 'tag.css', foreground: '7AC0A0' },
    { token: 'tag.id.css', foreground: '5A9BE6' },
    { token: 'tag.class.css', foreground: '7AC0A0' },
    
    // Markdown
    { token: 'markup.heading', foreground: '80FFB5' },
    { token: 'markup.bold', foreground: 'D4A5E8', fontStyle: 'bold' },
    { token: 'markup.italic', foreground: '5A9BE6', fontStyle: 'italic' },
    { token: 'markup.underline.link', foreground: '88C8F0' },
    { token: 'markup.inline.raw', foreground: '80FFB5' },
    { token: 'string.other.link', foreground: 'D4A5E8' },
    
    // Invalid
    { token: 'invalid', foreground: 'FF8090' },
    { token: 'invalid.illegal', foreground: 'FF8090' },

    // ========== Language specific - C++ ==========
    { token: 'keyword.cpp', foreground: '89DDFF' },
    { token: 'keyword.control.cpp', foreground: '89DDFF' },
    { token: 'keyword.operator.cpp', foreground: 'B8C0D0' },
    { token: 'keyword.operator.new.cpp', foreground: '89DDFF' },
    { token: 'storage.type.cpp', foreground: '89DDFF' },
    { token: 'storage.modifier.cpp', foreground: '89DDFF' },
    { token: 'storage.type.primitive.cpp', foreground: '7AC0A0' },
    { token: 'storage.type.built-in.cpp', foreground: '7AC0A0' },
    { token: 'storage.type.built-in.primitive.cpp', foreground: '7AC0A0' },
    { token: 'entity.name.type.cpp', foreground: '7AC0A0' },
    { token: 'entity.name.type.class.cpp', foreground: '7AC0A0' },
    { token: 'entity.name.type.struct.cpp', foreground: '7AC0A0' },
    { token: 'entity.name.type.enum.cpp', foreground: '7AC0A0' },
    { token: 'entity.name.type.template.cpp', foreground: '7AC0A0' },
    { token: 'entity.name.function.cpp', foreground: 'C2A0FD' },
    { token: 'entity.name.function.member.cpp', foreground: 'C2A0FD' },
    { token: 'entity.name.function.operator.cpp', foreground: 'C2A0FD' },
    { token: 'entity.name.namespace.cpp', foreground: 'C2A0FD' },
    { token: 'variable.cpp', foreground: 'FFE5A0' },
    { token: 'variable.other.cpp', foreground: 'FFE5A0' },
    { token: 'variable.parameter.cpp', foreground: 'FFE5A0' },
    { token: 'variable.other.member.cpp', foreground: 'FFE5A0' },
    { token: 'variable.other.local.cpp', foreground: 'FFE5A0' },
    { token: 'variable.other.global.cpp', foreground: 'FFE5A0' },
    { token: 'constant.numeric.cpp', foreground: 'FFE5A0' },
    { token: 'string.quoted.cpp', foreground: 'E8B89C' },
    { token: 'comment.cpp', foreground: '7A7595' },
    { token: 'comment.line.cpp', foreground: '7A7595' },
    { token: 'comment.block.cpp', foreground: '7A7595' },
    { token: 'meta.preprocessor.cpp', foreground: 'C2A0FD' },
    { token: 'keyword.control.directive.cpp', foreground: 'C2A0FD' },
    { token: 'entity.name.function.preprocessor.cpp', foreground: 'C2A0FD' },
    { token: 'punctuation.definition.directive.cpp', foreground: 'C2A0FD' },
    { token: 'support.type.cpp', foreground: '7AC0A0' },
    { token: 'support.class.cpp', foreground: '7AC0A0' },
    { token: 'support.function.cpp', foreground: 'C2A0FD' },
    { token: 'identifier.cpp', foreground: 'FFE5A0' },
    { token: 'type.identifier.cpp', foreground: '7AC0A0' },

    // ========== Language specific - Rust ==========
    { token: 'keyword.rust', foreground: '89DDFF' },
    { token: 'keyword.control.rust', foreground: '89DDFF' },
    { token: 'keyword.other.rust', foreground: '89DDFF' },
    { token: 'storage.type.rust', foreground: '89DDFF' },
    { token: 'storage.modifier.rust', foreground: '89DDFF' },
    { token: 'entity.name.type.rust', foreground: '7AC0A0' },
    { token: 'entity.name.type.struct.rust', foreground: '7AC0A0' },
    { token: 'entity.name.type.enum.rust', foreground: '7AC0A0' },
    { token: 'entity.name.type.trait.rust', foreground: '7AC0A0' },
    { token: 'entity.name.type.module.rust', foreground: 'C2A0FD' },
    { token: 'entity.name.function.rust', foreground: 'C2A0FD' },
    { token: 'entity.name.function.macro.rust', foreground: 'C2A0FD' },
    { token: 'entity.name.namespace.rust', foreground: 'C2A0FD' },
    { token: 'entity.name.lifetime.rust', foreground: '7AC0A0' },
    { token: 'variable.rust', foreground: 'FFE5A0' },
    { token: 'variable.other.rust', foreground: 'FFE5A0' },
    { token: 'variable.parameter.rust', foreground: 'FFE5A0' },
    { token: 'variable.language.rust', foreground: '80FFB5' },
    { token: 'constant.numeric.rust', foreground: 'FFE5A0' },
    { token: 'string.quoted.rust', foreground: 'E8B89C' },
    { token: 'comment.rust', foreground: '7A7595' },
    { token: 'comment.line.rust', foreground: '7A7595' },
    { token: 'comment.block.rust', foreground: '7A7595' },
    { token: 'support.type.rust', foreground: '7AC0A0' },
    { token: 'support.function.rust', foreground: 'C2A0FD' },
    { token: 'support.macro.rust', foreground: 'C2A0FD' },
    { token: 'lifetime.rust', foreground: '7AC0A0' },
    { token: 'macro.rust', foreground: 'C2A0FD' },
    { token: 'attribute.rust', foreground: 'C2A0FD' },
    { token: 'meta.attribute.rust', foreground: 'C2A0FD' },
    { token: 'identifier.rust', foreground: 'FFE5A0' },
    { token: 'type.identifier.rust', foreground: '7AC0A0' },

    // ========== Language specific - Go ==========
    { token: 'keyword.go', foreground: '89DDFF' },
    { token: 'keyword.control.go', foreground: '89DDFF' },
    { token: 'keyword.function.go', foreground: '89DDFF' },
    { token: 'keyword.package.go', foreground: '89DDFF' },
    { token: 'keyword.import.go', foreground: '89DDFF' },
    { token: 'keyword.type.go', foreground: '89DDFF' },
    { token: 'keyword.struct.go', foreground: '89DDFF' },
    { token: 'keyword.interface.go', foreground: '89DDFF' },
    { token: 'keyword.map.go', foreground: '89DDFF' },
    { token: 'keyword.chan.go', foreground: '89DDFF' },
    { token: 'keyword.var.go', foreground: '89DDFF' },
    { token: 'keyword.const.go', foreground: '89DDFF' },
    { token: 'storage.type.go', foreground: '7AC0A0' },
    { token: 'storage.type.numeric.go', foreground: '7AC0A0' },
    { token: 'storage.type.string.go', foreground: '7AC0A0' },
    { token: 'storage.type.boolean.go', foreground: '7AC0A0' },
    { token: 'storage.type.byte.go', foreground: '7AC0A0' },
    { token: 'storage.type.error.go', foreground: '7AC0A0' },
    { token: 'entity.name.type.go', foreground: '7AC0A0' },
    { token: 'entity.name.type.interface.go', foreground: '7AC0A0' },
    { token: 'entity.name.type.struct.go', foreground: '7AC0A0' },
    { token: 'entity.name.function.go', foreground: 'C2A0FD' },
    { token: 'entity.name.package.go', foreground: 'C2A0FD' },
    { token: 'variable.go', foreground: 'FFE5A0' },
    { token: 'variable.other.go', foreground: 'FFE5A0' },
    { token: 'variable.parameter.go', foreground: 'FFE5A0' },
    { token: 'variable.other.field.go', foreground: 'FFE5A0' },
    { token: 'variable.other.member.go', foreground: 'FFE5A0' },
    { token: 'constant.go', foreground: 'FFE5A0' },
    { token: 'constant.numeric.go', foreground: 'FFE5A0' },
    { token: 'constant.language.go', foreground: 'E8B89C' },
    { token: 'string.quoted.go', foreground: 'E8B89C' },
    { token: 'comment.go', foreground: '7A7595' },
    { token: 'comment.line.go', foreground: '7A7595' },
    { token: 'comment.block.go', foreground: '7A7595' },
    { token: 'support.function.go', foreground: 'C2A0FD' },
    { token: 'support.function.builtin.go', foreground: 'C2A0FD' },
    { token: 'support.type.builtin.go', foreground: '7AC0A0' },
    { token: 'package.go', foreground: 'C2A0FD' },
    { token: 'type.go', foreground: '7AC0A0' },
    { token: 'struct.go', foreground: '7AC0A0' },
    { token: 'interface.go', foreground: '7AC0A0' },
    { token: 'function.go', foreground: 'C2A0FD' },
    { token: 'method.go', foreground: 'C2A0FD' },
    { token: 'property.go', foreground: 'FFE5A0' },
    { token: 'identifier.go', foreground: 'FFE5A0' },
    { token: 'type.identifier.go', foreground: '7AC0A0' },

    // ========== Language specific - Python ==========
    { token: 'keyword.python', foreground: '89DDFF' },
    { token: 'keyword.control.python', foreground: '89DDFF' },
    { token: 'keyword.control.flow.python', foreground: '89DDFF' },
    { token: 'keyword.control.import.python', foreground: '89DDFF' },
    { token: 'keyword.operator.python', foreground: 'B8C0D0' },
    { token: 'keyword.operator.logical.python', foreground: '89DDFF' },
    { token: 'storage.type.python', foreground: '89DDFF' },
    { token: 'storage.type.function.python', foreground: '89DDFF' },
    { token: 'storage.type.class.python', foreground: '89DDFF' },
    { token: 'entity.name.type.python', foreground: '7AC0A0' },
    { token: 'entity.name.type.class.python', foreground: '7AC0A0' },
    { token: 'entity.name.function.python', foreground: 'C2A0FD' },
    { token: 'entity.name.function.decorator.python', foreground: 'C2A0FD' },
    { token: 'variable.python', foreground: 'FFE5A0' },
    { token: 'variable.other.python', foreground: 'FFE5A0' },
    { token: 'variable.parameter.python', foreground: 'FFE5A0' },
    { token: 'variable.parameter.function.python', foreground: 'FFE5A0' },
    { token: 'variable.language.python', foreground: '80FFB5' },
    { token: 'variable.language.self.python', foreground: '80FFB5' },
    { token: 'constant.numeric.python', foreground: 'FFE5A0' },
    { token: 'constant.language.python', foreground: 'E8B89C' },
    { token: 'string.quoted.python', foreground: 'E8B89C' },
    { token: 'string.quoted.docstring.python', foreground: '8A85A5' },
    { token: 'comment.python', foreground: '7A7595' },
    { token: 'comment.line.python', foreground: '7A7595' },
    { token: 'support.type.python', foreground: '7AC0A0' },
    { token: 'support.function.python', foreground: 'C2A0FD' },
    { token: 'support.function.builtin.python', foreground: 'C2A0FD' },
    { token: 'support.function.magic.python', foreground: 'C2A0FD' },
    { token: 'meta.function.decorator.python', foreground: 'C2A0FD' },
    { token: 'decorator.python', foreground: 'C2A0FD' },
    { token: 'identifier.python', foreground: 'FFE5A0' },
    { token: 'type.identifier.python', foreground: '7AC0A0' },

    // ========== Language specific - TypeScript/JavaScript ==========
    { token: 'keyword.typescript', foreground: '89DDFF' },
    { token: 'keyword.javascript', foreground: '89DDFF' },
    { token: 'keyword.control.typescript', foreground: '89DDFF' },
    { token: 'keyword.control.javascript', foreground: '89DDFF' },
    { token: 'storage.type.typescript', foreground: '89DDFF' },
    { token: 'storage.type.javascript', foreground: '89DDFF' },
    { token: 'entity.name.type.typescript', foreground: '7AC0A0' },
    { token: 'entity.name.type.interface.typescript', foreground: '7AC0A0' },
    { token: 'entity.name.type.class.typescript', foreground: '7AC0A0' },
    { token: 'entity.name.function.typescript', foreground: 'C2A0FD' },
    { token: 'entity.name.function.javascript', foreground: 'C2A0FD' },
    { token: 'variable.typescript', foreground: 'FFE5A0' },
    { token: 'variable.javascript', foreground: 'FFE5A0' },
    { token: 'variable.parameter.typescript', foreground: 'FFE5A0' },
    { token: 'variable.parameter.javascript', foreground: 'FFE5A0' },
    { token: 'variable.other.property.typescript', foreground: 'FFE5A0' },
    { token: 'variable.other.property.javascript', foreground: 'FFE5A0' },
    { token: 'constant.numeric.typescript', foreground: 'FFE5A0' },
    { token: 'constant.numeric.javascript', foreground: 'FFE5A0' },
    { token: 'string.quoted.typescript', foreground: 'E8B89C' },
    { token: 'string.quoted.javascript', foreground: 'E8B89C' },
    { token: 'string.template.typescript', foreground: 'E8B89C' },
    { token: 'string.template.javascript', foreground: 'E8B89C' },
    { token: 'comment.typescript', foreground: '7A7595' },
    { token: 'comment.javascript', foreground: '7A7595' },
    { token: 'support.type.typescript', foreground: '7AC0A0' },
    { token: 'support.class.typescript', foreground: '7AC0A0' },
    { token: 'support.function.typescript', foreground: 'C2A0FD' },
    { token: 'support.function.javascript', foreground: 'C2A0FD' },
    { token: 'identifier.typescript', foreground: 'FFE5A0' },
    { token: 'identifier.javascript', foreground: 'FFE5A0' },
    { token: 'type.identifier.typescript', foreground: '7AC0A0' },

    // ========== Language specific - Dart ==========
    { token: 'keyword.dart', foreground: '89DDFF' },
    { token: 'keyword.control.dart', foreground: '89DDFF' },
    { token: 'keyword.operator.dart', foreground: 'B8C0D0' },
    { token: 'storage.modifier.dart', foreground: '89DDFF' },
    { token: 'storage.type.dart', foreground: '7AC0A0' },
    { token: 'storage.type.primitive.dart', foreground: '7AC0A0' },
    { token: 'entity.name.type.dart', foreground: '7AC0A0' },
    { token: 'entity.name.type.class.dart', foreground: '7AC0A0' },
    { token: 'entity.name.type.enum.dart', foreground: '7AC0A0' },
    { token: 'entity.name.function.dart', foreground: 'C2A0FD' },
    { token: 'support.class.dart', foreground: '7AC0A0' },
    { token: 'support.function.dart', foreground: 'C2A0FD' },
    { token: 'variable.dart', foreground: 'FFE5A0' },
    { token: 'variable.other.dart', foreground: 'FFE5A0' },
    { token: 'variable.other.readwrite.dart', foreground: 'FFE5A0' },
    { token: 'variable.parameter.dart', foreground: 'FFE5A0' },
    { token: 'variable.other.property.dart', foreground: 'FFE5A0' },
    { token: 'variable.other.constant.dart', foreground: 'FFE5A0' },
    { token: 'variable.other.enummember.dart', foreground: 'FFE5A0' },
    { token: 'constant.dart', foreground: 'FFE5A0' },
    { token: 'constant.numeric.dart', foreground: 'FFE5A0' },
    { token: 'constant.language.dart', foreground: 'E8B89C' },
    { token: 'constant.other.dart', foreground: 'FFE5A0' },
    { token: 'string.dart', foreground: 'E8B89C' },
    { token: 'string.quoted.dart', foreground: 'E8B89C' },
    { token: 'string.interpolated.dart', foreground: 'E8B89C' },
    { token: 'comment.dart', foreground: '7A7595' },
    { token: 'comment.line.dart', foreground: '7A7595' },
    { token: 'comment.block.dart', foreground: '7A7595' },
    { token: 'meta.annotation.dart', foreground: 'C2A0FD' },
    { token: 'storage.type.annotation.dart', foreground: 'C2A0FD' },
    { token: 'identifier.dart', foreground: 'FFE5A0' },
    { token: 'type.identifier.dart', foreground: '7AC0A0' },

    // ========== Language specific - HTML ==========
    { token: 'tag.html', foreground: '80FFB5' },
    { token: 'metatag.content.html', foreground: '80FFB5' },
    { token: 'attribute.name.html', foreground: 'FFE5A0' },
    { token: 'attribute.value.html', foreground: 'E8B89C' },
    { token: 'string.html', foreground: 'E8B89C' },
    { token: 'comment.html', foreground: '7A7595' },
    { token: 'delimiter.html', foreground: 'B8C0D0' },
    
    // ========== Language specific - CSS ==========
    { token: 'tag.css', foreground: '7AC0A0' },
    { token: 'tag.id.css', foreground: '5A9BE6' },
    { token: 'tag.class.css', foreground: '7AC0A0' },
    { token: 'attribute.name.css', foreground: 'FFE5A0' },
    { token: 'attribute.value.css', foreground: 'C0C8D8' },
    { token: 'attribute.value.number.css', foreground: 'FFE5A0' },
    { token: 'attribute.value.unit.css', foreground: 'E8B89C' },
    { token: 'keyword.css', foreground: '89DDFF' },
    { token: 'string.css', foreground: 'E8B89C' },
    { token: 'comment.css', foreground: '7A7595' },
    { token: 'delimiter.css', foreground: 'B8C0D0' },
    
    // ========== Language specific - JSON ==========
    { token: 'string.key.json', foreground: 'FFE5A0' },
    { token: 'string.value.json', foreground: 'E8B89C' },
    { token: 'number.json', foreground: 'FFE5A0' },
    { token: 'keyword.json', foreground: 'E8B89C' },
    { token: 'delimiter.json', foreground: 'B8C0D0' },
  ],
  colors: {
    'editor.background': '#14101A',
    'editor.foreground': '#B8BFD0',
    'editor.lineHighlightBackground': '#1E1828',
    'editor.lineHighlightBorder': '#2E284000',
    'editor.selectionBackground': '#7E5A9E55',
    'editor.selectionForeground': '#FFFFFF',
    'editor.inactiveSelectionBackground': '#7E5A9E35',
    'editorCursor.foreground': '#E8B4FF',
    'editorLineNumber.foreground': '#5A5570',
    'editorLineNumber.activeForeground': '#B8BFD0',
    'editorIndentGuide.background': '#3D365060',
    'editorIndentGuide.activeBackground': '#3D3650',
    'editorWhitespace.foreground': '#3D365080',
    'editorBracketMatch.background': '#9D8CCC35',
    'editorBracketMatch.border': '#9D8CCC70',
    'editorBracketHighlight.foreground1': '#89DDFF',
    'editorBracketHighlight.foreground2': '#C0A0FF',
    'editorBracketHighlight.foreground3': '#80FFB5',
    'editorBracketHighlight.foreground4': '#E8A080',
    'editorBracketHighlight.foreground5': '#5AE89A',
    'editorBracketHighlight.foreground6': '#E8A0D0',
    'editor.findMatchBackground': '#3D7A5090',
    'editor.findMatchHighlightBackground': '#3D7A5060',
    'editor.findMatchBorder': '#5AE89ADD',
    'editor.wordHighlightBackground': '#9D8CCC25',
    'editor.wordHighlightBorder': '#9D8CCC45',
    'editorWidget.background': '#1A1520',
    'editorWidget.border': '#3D3650',
    'editorSuggestWidget.background': '#1A1520',
    'editorSuggestWidget.border': '#3D3650',
    'editorSuggestWidget.selectedBackground': '#2A2435',
    'editorHoverWidget.background': '#1A1520',
    'editorHoverWidget.border': '#3D3650',
    'scrollbarSlider.background': '#9D8CCC22',
    'scrollbarSlider.hoverBackground': '#9D8CCC40',
    'scrollbarSlider.activeBackground': '#9D8CCC55',
  },
}
