/**
 * Semantic Token Colors
 * 
 * Language server provided semantic highlighting.
 */

import { palette, withOpacity } from "../palette";
import type { SemanticTokenColor } from "./types";

export const semanticTokenColors: SemanticTokenColor = {
  // ============ Namespaces ============
  "namespace": withOpacity(palette.lavender, "medium"),
  "namespace.declaration": withOpacity(palette.lavender, "high"),
  "namespace.defaultLibrary": withOpacity(palette.lavender, "subtle"),

  // ============ Types ============
  "type": withOpacity(palette.teal, "medium"),
  "type.declaration": withOpacity(palette.teal, "high"),
  "type.defaultLibrary": withOpacity(palette.teal, "subtle"),
  "class": withOpacity(palette.teal, "medium"),
  "class.declaration": withOpacity(palette.teal, "high"),
  "class.defaultLibrary": withOpacity(palette.teal, "subtle"),
  "interface": withOpacity(palette.teal, "medium"),
  "interface.declaration": withOpacity(palette.teal, "high"),
  "interface.defaultLibrary": withOpacity(palette.teal, "subtle"),
  "struct": withOpacity(palette.teal, "medium"),
  "struct.declaration": withOpacity(palette.teal, "high"),
  "enum": withOpacity(palette.teal, "medium"),
  "enum.declaration": withOpacity(palette.teal, "high"),
  "enum.defaultLibrary": withOpacity(palette.teal, "subtle"),

  // ============ Enum Members ============
  "enumMember": withOpacity(palette.yellow, "low"),
  "enumMember.declaration": withOpacity(palette.yellow, "high"),
  "enumMember.defaultLibrary": withOpacity(palette.yellow, "subtle"),
  "enumMember.readonly": withOpacity(palette.yellow, "low"),
  "enumMember.static": withOpacity(palette.yellow, "low"),
  "enumMember.readonly.defaultLibrary": withOpacity(palette.yellow, "subtle"),

  // ============ Type Parameters ============
  "typeParameter": withOpacity(palette.teal, "subtle"),
  "typeParameter.declaration": withOpacity(palette.teal, "medium"),

  // ============ Functions ============
  "function": withOpacity(palette.lavender, "high"),
  "function.declaration": palette.lavender,
  "function.defaultLibrary": withOpacity(palette.lavender, "medium"),
  "function.static": withOpacity(palette.lavender, "high"),
  "method": withOpacity(palette.lavender, "high"),
  "method.declaration": palette.lavender,
  "method.defaultLibrary": withOpacity(palette.lavender, "medium"),
  "method.static": withOpacity(palette.lavender, "high"),
  "macro": withOpacity(palette.lavender, "medium"),
  "macro.declaration": withOpacity(palette.lavender, "high"),

  // ============ Variables ============
  "variable": withOpacity(palette.yellow, "low"),
  "variable.declaration": palette.yellow,
  "variable.readonly": withOpacity(palette.yellow, "low"),
  "variable.readonly.defaultLibrary": withOpacity(palette.yellow, "subtle"),
  "variable.defaultLibrary": withOpacity(palette.yellow, "low"),
  "variable.static": withOpacity(palette.yellow, "low"),
  "variable.static.readonly": withOpacity(palette.yellow, "low"),
  "variable.local": withOpacity(palette.yellow, "low"),
  "variable.local.declaration": palette.yellow,

  // ============ Parameters ============
  "parameter": withOpacity(palette.yellow, "low"),
  "parameter.declaration": palette.yellow,
  "parameter.readonly": withOpacity(palette.yellow, "subtle"),

  // ============ Properties ============
  "property": withOpacity(palette.yellow, "low"),
  "property.declaration": withOpacity(palette.yellow, "high"),
  "property.readonly": withOpacity(palette.yellow, "low"),
  "property.static": withOpacity(palette.yellow, "low"),
  "property.static.readonly": withOpacity(palette.yellow, "low"),
  "property.defaultLibrary": withOpacity(palette.yellow, "subtle"),

  // ============ Decorators ============
  "decorator": withOpacity(palette.lavender, "medium"),
  "decorator.declaration": withOpacity(palette.lavender, "high"),
  "event": withOpacity(palette.lavender, "medium"),
  "event.declaration": withOpacity(palette.lavender, "high"),

  // ============ Other ============
  "label": "#C0C8D8DD",
  "keyword": withOpacity(palette.sky, "medium"),
  "keyword.control": withOpacity(palette.sky, "medium"),
  "comment": "#7A7595",
  "string": "#E8B89CBB",
  "number": "#E8B89CAA",
  "regexp": withOpacity(palette.green, "medium"),
  "operator": "#B8C0D0",

  // ============ Modifiers ============
  "*.static": withOpacity(palette.yellow, "low"),
  "*.readonly": withOpacity(palette.yellow, "low"),
  "*.defaultLibrary": { foreground: withOpacity(palette.teal, "subtle") },
  "*.declaration": { fontStyle: "" },
  "*.modification": { fontStyle: "underline" },
  "*.deprecated": { fontStyle: "strikethrough" },

  // ============ Special ============
  "selfKeyword": withOpacity(palette.green, "medium"),
  "selfParameter": withOpacity(palette.green, "medium"),
  "builtinType": withOpacity(palette.teal, "subtle"),
  "formatSpecifier": withOpacity(palette.green, "medium"),
  "escapeSequence": withOpacity(palette.green, "medium"),
  "lifetime": withOpacity(palette.teal, "subtle"),
  "source": "#C0C8D8",
  "text": "#C0C8D8",
  "punctuation": "#B8C0D0",
  "meta": "#C0C8D8",
};

// Language-specific semantic tokens
export const languageSemanticTokens: SemanticTokenColor = {
  // ============ JavaScript ============
  "class:javascript": withOpacity(palette.teal, "medium"),
  "class.defaultLibrary:javascript": withOpacity(palette.teal, "subtle"),
  "enum:javascript": withOpacity(palette.teal, "medium"),
  "enumMember:javascript": withOpacity(palette.yellow, "low"),
  "interface:javascript": withOpacity(palette.teal, "medium"),
  "type:javascript": withOpacity(palette.teal, "medium"),
  "type.defaultLibrary:javascript": withOpacity(palette.teal, "subtle"),
  "function:javascript": withOpacity(palette.lavender, "high"),
  "function.defaultLibrary:javascript": withOpacity(palette.lavender, "medium"),
  "method:javascript": withOpacity(palette.lavender, "high"),
  "method.defaultLibrary:javascript": withOpacity(palette.lavender, "medium"),
  "variable:javascript": withOpacity(palette.yellow, "low"),
  "variable.readonly:javascript": withOpacity(palette.yellow, "low"),
  "variable.defaultLibrary:javascript": withOpacity(palette.yellow, "low"),
  "parameter:javascript": withOpacity(palette.yellow, "low"),
  "property:javascript": withOpacity(palette.yellow, "low"),
  "property.readonly:javascript": withOpacity(palette.yellow, "low"),
  "property.static:javascript": withOpacity(palette.yellow, "low"),
  "property.defaultLibrary:javascript": withOpacity(palette.yellow, "subtle"),
  "keyword:javascript": withOpacity(palette.sky, "medium"),
  "string:javascript": "#E8B89CBB",
  "number:javascript": "#E8B89CAA",
  "regexp:javascript": withOpacity(palette.green, "medium"),
  "comment:javascript": "#7A7595",
  "*.readonly:javascript": withOpacity(palette.yellow, "low"),
  "*.defaultLibrary:javascript": withOpacity(palette.teal, "subtle"),

  // ============ TypeScript ============
  "namespace:typescript": withOpacity(palette.lavender, "medium"),
  "class:typescript": withOpacity(palette.teal, "medium"),
  "class.defaultLibrary:typescript": withOpacity(palette.teal, "subtle"),
  "enum:typescript": withOpacity(palette.teal, "medium"),
  "enumMember:typescript": withOpacity(palette.yellow, "low"),
  "interface:typescript": withOpacity(palette.teal, "medium"),
  "type:typescript": withOpacity(palette.teal, "medium"),
  "type.defaultLibrary:typescript": withOpacity(palette.teal, "subtle"),
  "typeParameter:typescript": withOpacity(palette.teal, "subtle"),
  "function:typescript": withOpacity(palette.lavender, "high"),
  "function.defaultLibrary:typescript": withOpacity(palette.lavender, "medium"),
  "method:typescript": withOpacity(palette.lavender, "high"),
  "method.defaultLibrary:typescript": withOpacity(palette.lavender, "medium"),
  "variable:typescript": withOpacity(palette.yellow, "low"),
  "variable.readonly:typescript": withOpacity(palette.yellow, "low"),
  "variable.defaultLibrary:typescript": withOpacity(palette.yellow, "low"),
  "parameter:typescript": withOpacity(palette.yellow, "low"),
  "property:typescript": withOpacity(palette.yellow, "low"),
  "property.readonly:typescript": withOpacity(palette.yellow, "low"),
  "property.static:typescript": withOpacity(palette.yellow, "low"),
  "property.defaultLibrary:typescript": withOpacity(palette.yellow, "subtle"),
  "keyword:typescript": withOpacity(palette.sky, "medium"),
  "string:typescript": "#E8B89CBB",
  "number:typescript": "#E8B89CAA",
  "regexp:typescript": withOpacity(palette.green, "medium"),
  "comment:typescript": "#7A7595",
  "decorator:typescript": withOpacity(palette.lavender, "medium"),
  "*.readonly:typescript": withOpacity(palette.yellow, "low"),
  "*.defaultLibrary:typescript": withOpacity(palette.teal, "subtle"),

  // ============ TypeScript React ============
  "namespace:typescriptreact": withOpacity(palette.lavender, "medium"),
  "class:typescriptreact": withOpacity(palette.teal, "medium"),
  "class.defaultLibrary:typescriptreact": withOpacity(palette.teal, "subtle"),
  "enum:typescriptreact": withOpacity(palette.teal, "medium"),
  "enumMember:typescriptreact": withOpacity(palette.yellow, "low"),
  "interface:typescriptreact": withOpacity(palette.teal, "medium"),
  "type:typescriptreact": withOpacity(palette.teal, "medium"),
  "type.defaultLibrary:typescriptreact": withOpacity(palette.teal, "subtle"),
  "typeParameter:typescriptreact": withOpacity(palette.teal, "subtle"),
  "function:typescriptreact": withOpacity(palette.lavender, "high"),
  "function.defaultLibrary:typescriptreact": withOpacity(palette.lavender, "medium"),
  "method:typescriptreact": withOpacity(palette.lavender, "high"),
  "method.defaultLibrary:typescriptreact": withOpacity(palette.lavender, "medium"),
  "variable:typescriptreact": withOpacity(palette.yellow, "low"),
  "variable.readonly:typescriptreact": withOpacity(palette.yellow, "low"),
  "variable.defaultLibrary:typescriptreact": withOpacity(palette.yellow, "low"),
  "parameter:typescriptreact": withOpacity(palette.yellow, "low"),
  "property:typescriptreact": withOpacity(palette.yellow, "low"),
  "property.readonly:typescriptreact": withOpacity(palette.yellow, "low"),
  "property.static:typescriptreact": withOpacity(palette.yellow, "low"),
  "property.defaultLibrary:typescriptreact": withOpacity(palette.yellow, "subtle"),
  "keyword:typescriptreact": withOpacity(palette.sky, "medium"),
  "string:typescriptreact": "#E8B89CBB",
  "number:typescriptreact": "#E8B89CAA",
  "regexp:typescriptreact": withOpacity(palette.green, "medium"),
  "comment:typescriptreact": "#7A7595",
  "decorator:typescriptreact": withOpacity(palette.lavender, "medium"),
  "*.readonly:typescriptreact": withOpacity(palette.yellow, "low"),
  "*.defaultLibrary:typescriptreact": withOpacity(palette.teal, "subtle"),

  // ============ JavaScript React ============
  "class:javascriptreact": withOpacity(palette.teal, "medium"),
  "class.defaultLibrary:javascriptreact": withOpacity(palette.teal, "subtle"),
  "enum:javascriptreact": withOpacity(palette.teal, "medium"),
  "enumMember:javascriptreact": withOpacity(palette.yellow, "low"),
  "interface:javascriptreact": withOpacity(palette.teal, "medium"),
  "type:javascriptreact": withOpacity(palette.teal, "medium"),
  "type.defaultLibrary:javascriptreact": withOpacity(palette.teal, "subtle"),
  "function:javascriptreact": withOpacity(palette.lavender, "high"),
  "function.defaultLibrary:javascriptreact": withOpacity(palette.lavender, "medium"),
  "method:javascriptreact": withOpacity(palette.lavender, "high"),
  "method.defaultLibrary:javascriptreact": withOpacity(palette.lavender, "medium"),
  "variable:javascriptreact": withOpacity(palette.yellow, "low"),
  "variable.readonly:javascriptreact": withOpacity(palette.yellow, "low"),
  "variable.defaultLibrary:javascriptreact": withOpacity(palette.yellow, "low"),
  "parameter:javascriptreact": withOpacity(palette.yellow, "low"),
  "property:javascriptreact": withOpacity(palette.yellow, "low"),
  "property.readonly:javascriptreact": withOpacity(palette.yellow, "low"),
  "property.static:javascriptreact": withOpacity(palette.yellow, "low"),
  "property.defaultLibrary:javascriptreact": withOpacity(palette.yellow, "subtle"),
  "keyword:javascriptreact": withOpacity(palette.sky, "medium"),
  "string:javascriptreact": "#E8B89CBB",
  "number:javascriptreact": "#E8B89CAA",
  "regexp:javascriptreact": withOpacity(palette.green, "medium"),
  "comment:javascriptreact": "#7A7595",
  "*.readonly:javascriptreact": withOpacity(palette.yellow, "low"),
  "*.defaultLibrary:javascriptreact": withOpacity(palette.teal, "subtle"),

  // ============ Python ============
  "namespace:python": withOpacity(palette.lavender, "medium"),
  "class:python": withOpacity(palette.teal, "medium"),
  "class.defaultLibrary:python": withOpacity(palette.teal, "subtle"),
  "enum:python": withOpacity(palette.teal, "medium"),
  "enumMember:python": withOpacity(palette.yellow, "low"),
  "type:python": withOpacity(palette.teal, "medium"),
  "type.defaultLibrary:python": withOpacity(palette.teal, "subtle"),
  "typeParameter:python": withOpacity(palette.teal, "subtle"),
  "function:python": withOpacity(palette.lavender, "high"),
  "function.defaultLibrary:python": withOpacity(palette.lavender, "medium"),
  "method:python": withOpacity(palette.lavender, "high"),
  "method.defaultLibrary:python": withOpacity(palette.lavender, "medium"),
  "variable:python": withOpacity(palette.yellow, "low"),
  "variable.readonly:python": withOpacity(palette.yellow, "low"),
  "variable.defaultLibrary:python": withOpacity(palette.yellow, "low"),
  "parameter:python": withOpacity(palette.yellow, "low"),
  "property:python": withOpacity(palette.yellow, "low"),
  "property.readonly:python": withOpacity(palette.yellow, "low"),
  "property.static:python": withOpacity(palette.yellow, "low"),
  "property.defaultLibrary:python": withOpacity(palette.yellow, "subtle"),
  "keyword:python": withOpacity(palette.sky, "medium"),
  "string:python": "#E8B89CBB",
  "number:python": "#E8B89CAA",
  "regexp:python": withOpacity(palette.green, "medium"),
  "comment:python": "#7A7595",
  "decorator:python": withOpacity(palette.lavender, "medium"),
  "selfParameter:python": withOpacity(palette.green, "medium"),
  "clsParameter:python": withOpacity(palette.green, "medium"),
  "magicFunction:python": withOpacity(palette.lavender, "medium"),
  "*.readonly:python": withOpacity(palette.yellow, "low"),
  "*.defaultLibrary:python": withOpacity(palette.teal, "subtle"),

  // ============ Rust ============
  "namespace:rust": withOpacity(palette.lavender, "medium"),
  "class:rust": withOpacity(palette.teal, "medium"),
  "struct:rust": withOpacity(palette.teal, "medium"),
  "enum:rust": withOpacity(palette.teal, "medium"),
  "enumMember:rust": withOpacity(palette.yellow, "low"),
  "union:rust": withOpacity(palette.teal, "medium"),
  "interface:rust": withOpacity(palette.teal, "medium"),
  "type:rust": withOpacity(palette.teal, "medium"),
  "type.defaultLibrary:rust": withOpacity(palette.teal, "subtle"),
  "typeParameter:rust": withOpacity(palette.teal, "subtle"),
  "typeAlias:rust": withOpacity(palette.teal, "medium"),
  "function:rust": withOpacity(palette.lavender, "high"),
  "function.defaultLibrary:rust": withOpacity(palette.lavender, "medium"),
  "method:rust": withOpacity(palette.lavender, "high"),
  "method.defaultLibrary:rust": withOpacity(palette.lavender, "medium"),
  "macro:rust": withOpacity(palette.lavender, "medium"),
  "variable:rust": withOpacity(palette.yellow, "low"),
  "variable.readonly:rust": withOpacity(palette.yellow, "low"),
  "variable.static:rust": withOpacity(palette.yellow, "low"),
  "variable.defaultLibrary:rust": withOpacity(palette.yellow, "low"),
  "parameter:rust": withOpacity(palette.yellow, "low"),
  "property:rust": withOpacity(palette.yellow, "low"),
  "property.readonly:rust": withOpacity(palette.yellow, "low"),
  "property.static:rust": withOpacity(palette.yellow, "low"),
  "property.defaultLibrary:rust": withOpacity(palette.yellow, "subtle"),
  "keyword:rust": withOpacity(palette.sky, "medium"),
  "string:rust": "#E8B89CBB",
  "number:rust": "#E8B89CAA",
  "comment:rust": "#7A7595",
  "lifetime:rust": withOpacity(palette.teal, "subtle"),
  "selfKeyword:rust": withOpacity(palette.green, "medium"),
  "selfTypeKeyword:rust": withOpacity(palette.teal, "medium"),
  "attribute:rust": withOpacity(palette.lavender, "medium"),
  "derive:rust": withOpacity(palette.lavender, "medium"),
  "builtinAttribute:rust": withOpacity(palette.lavender, "subtle"),
  "formatSpecifier:rust": withOpacity(palette.green, "medium"),
  "escapeSequence:rust": withOpacity(palette.green, "medium"),
  "unresolvedReference:rust": withOpacity(palette.maroon, "medium"),
  "*.mutable:rust": { fontStyle: "underline" },
  "*.unsafe:rust": { foreground: withOpacity(palette.maroon, "medium") },
  "*.consuming:rust": { fontStyle: "italic" },
  "*.callable:rust": withOpacity(palette.lavender, "high"),
  "*.readonly:rust": withOpacity(palette.yellow, "low"),
  "*.defaultLibrary:rust": withOpacity(palette.teal, "subtle"),

  // ============ Dart ============
  "class:dart": withOpacity(palette.teal, "medium"),
  "class.defaultLibrary:dart": withOpacity(palette.teal, "subtle"),
  "enum:dart": withOpacity(palette.teal, "medium"),
  "enum.defaultLibrary:dart": withOpacity(palette.teal, "subtle"),
  "enumMember:dart": withOpacity(palette.yellow, "low"),
  "enumMember.defaultLibrary:dart": withOpacity(palette.yellow, "subtle"),
  "type:dart": withOpacity(palette.teal, "medium"),
  "type.defaultLibrary:dart": withOpacity(palette.teal, "subtle"),
  "typeParameter:dart": withOpacity(palette.teal, "subtle"),
  "function:dart": withOpacity(palette.lavender, "high"),
  "function.defaultLibrary:dart": withOpacity(palette.lavender, "medium"),
  "method:dart": withOpacity(palette.lavender, "high"),
  "method.defaultLibrary:dart": withOpacity(palette.lavender, "medium"),
  "variable:dart": withOpacity(palette.yellow, "low"),
  "variable.readonly:dart": withOpacity(palette.yellow, "low"),
  "variable.defaultLibrary:dart": withOpacity(palette.yellow, "low"),
  "parameter:dart": withOpacity(palette.yellow, "low"),
  "property:dart": withOpacity(palette.yellow, "low"),
  "property.declaration:dart": withOpacity(palette.yellow, "high"),
  "property.readonly:dart": withOpacity(palette.yellow, "low"),
  "property.static:dart": withOpacity(palette.yellow, "low"),
  "property.defaultLibrary:dart": withOpacity(palette.yellow, "subtle"),
  "keyword:dart": withOpacity(palette.sky, "medium"),
  "string:dart": "#E8B89CBB",
  "number:dart": "#E8B89CAA",
  "comment:dart": "#7A7595",
  "annotation:dart": withOpacity(palette.lavender, "medium"),
  "source:dart": "#C0C8D8",
  "*.static:dart": withOpacity(palette.yellow, "low"),
  "*.readonly:dart": withOpacity(palette.yellow, "low"),
  "*.defaultLibrary:dart": withOpacity(palette.teal, "subtle"),

  // ============ Go ============
  "namespace:go": withOpacity(palette.lavender, "medium"),
  "type:go": withOpacity(palette.teal, "medium"),
  "type.defaultLibrary:go": withOpacity(palette.teal, "subtle"),
  "struct:go": withOpacity(palette.teal, "medium"),
  "interface:go": withOpacity(palette.teal, "medium"),
  "function:go": withOpacity(palette.lavender, "high"),
  "function.defaultLibrary:go": withOpacity(palette.lavender, "medium"),
  "method:go": withOpacity(palette.lavender, "high"),
  "method.defaultLibrary:go": withOpacity(palette.lavender, "medium"),
  "variable:go": withOpacity(palette.yellow, "low"),
  "variable.readonly:go": withOpacity(palette.yellow, "low"),
  "variable.defaultLibrary:go": withOpacity(palette.yellow, "low"),
  "parameter:go": withOpacity(palette.yellow, "low"),
  "property:go": withOpacity(palette.yellow, "low"),
  "property.readonly:go": withOpacity(palette.yellow, "low"),
  "keyword:go": withOpacity(palette.sky, "medium"),
  "string:go": "#E8B89CBB",
  "number:go": "#E8B89CAA",
  "comment:go": "#7A7595",
  "*.readonly:go": withOpacity(palette.yellow, "low"),
  "*.defaultLibrary:go": withOpacity(palette.teal, "subtle"),

  // ============ C++ ============
  "namespace:cpp": withOpacity(palette.lavender, "medium"),
  "type:cpp": withOpacity(palette.teal, "medium"),
  "type.defaultLibrary:cpp": withOpacity(palette.teal, "subtle"),
  "class:cpp": withOpacity(palette.teal, "medium"),
  "class.defaultLibrary:cpp": withOpacity(palette.teal, "subtle"),
  "struct:cpp": withOpacity(palette.teal, "medium"),
  "enum:cpp": withOpacity(palette.teal, "medium"),
  "enumMember:cpp": withOpacity(palette.yellow, "low"),
  "templateType:cpp": withOpacity(palette.teal, "subtle"),
  "function:cpp": withOpacity(palette.lavender, "high"),
  "function.defaultLibrary:cpp": withOpacity(palette.lavender, "medium"),
  "templateFunction:cpp": withOpacity(palette.lavender, "high"),
  "method:cpp": withOpacity(palette.lavender, "high"),
  "method.static:cpp": withOpacity(palette.lavender, "high"),
  "method.defaultLibrary:cpp": withOpacity(palette.lavender, "medium"),
  "operatorOverload:cpp": withOpacity(palette.lavender, "high"),
  "memberOperatorOverload:cpp": withOpacity(palette.lavender, "high"),
  "macro:cpp": withOpacity(palette.lavender, "medium"),
  "variable:cpp": withOpacity(palette.yellow, "low"),
  "variable.local:cpp": withOpacity(palette.yellow, "low"),
  "variable.global:cpp": withOpacity(palette.yellow, "low"),
  "variable.readonly:cpp": withOpacity(palette.yellow, "low"),
  "variable.defaultLibrary:cpp": withOpacity(palette.yellow, "low"),
  "parameter:cpp": withOpacity(palette.yellow, "low"),
  "property:cpp": withOpacity(palette.yellow, "low"),
  "property.static:cpp": withOpacity(palette.yellow, "low"),
  "property.readonly:cpp": withOpacity(palette.yellow, "low"),
  "keyword:cpp": withOpacity(palette.sky, "medium"),
  "newOperator:cpp": withOpacity(palette.sky, "medium"),
  "string:cpp": "#E8B89CBB",
  "number:cpp": "#E8B89CAA",
  "numberLiteral:cpp": "#E8B89CAA",
  "stringLiteral:cpp": "#E8B89CBB",
  "customLiteral:cpp": "#E8B89CBB",
  "comment:cpp": "#7A7595",
  "label:cpp": "#C0C8D8DD",
  "typeParameter:cpp": withOpacity(palette.teal, "subtle"),
  "concept:cpp": withOpacity(palette.teal, "medium"),
  "genericType:cpp": withOpacity(palette.teal, "subtle"),
  "referenceType:cpp": withOpacity(palette.teal, "medium"),
  "valueType:cpp": withOpacity(palette.teal, "medium"),
  "cliProperty:cpp": withOpacity(palette.yellow, "low"),
  "event:cpp": withOpacity(palette.lavender, "medium"),
  "*.readonly:cpp": withOpacity(palette.yellow, "low"),
  "*.static:cpp": withOpacity(palette.yellow, "low"),
  "*.defaultLibrary:cpp": withOpacity(palette.teal, "subtle"),

  // ============ Vue ============
  "component:vue": withOpacity(palette.teal, "medium"),
  "class:vue": withOpacity(palette.teal, "medium"),
  "enum:vue": withOpacity(palette.teal, "medium"),
  "enumMember:vue": withOpacity(palette.yellow, "low"),
  "interface:vue": withOpacity(palette.teal, "medium"),
  "type:vue": withOpacity(palette.teal, "medium"),
  "type.defaultLibrary:vue": withOpacity(palette.teal, "subtle"),
  "typeParameter:vue": withOpacity(palette.teal, "subtle"),
  "function:vue": withOpacity(palette.lavender, "high"),
  "function.defaultLibrary:vue": withOpacity(palette.lavender, "medium"),
  "method:vue": withOpacity(palette.lavender, "high"),
  "method.defaultLibrary:vue": withOpacity(palette.lavender, "medium"),
  "variable:vue": withOpacity(palette.yellow, "low"),
  "variable.readonly:vue": withOpacity(palette.yellow, "low"),
  "variable.defaultLibrary:vue": withOpacity(palette.yellow, "low"),
  "parameter:vue": withOpacity(palette.yellow, "low"),
  "property:vue": withOpacity(palette.yellow, "low"),
  "property.readonly:vue": withOpacity(palette.yellow, "low"),
  "property.static:vue": withOpacity(palette.yellow, "low"),
  "property.defaultLibrary:vue": withOpacity(palette.yellow, "subtle"),
  "keyword:vue": withOpacity(palette.sky, "medium"),
  "string:vue": "#E8B89CBB",
  "number:vue": "#E8B89CAA",
  "comment:vue": "#7A7595",
  "decorator:vue": withOpacity(palette.lavender, "medium"),
  "*.readonly:vue": withOpacity(palette.yellow, "low"),
  "*.defaultLibrary:vue": withOpacity(palette.teal, "subtle"),
};
